# Please note that this CircleCI pipeline is much different from the upstream (https://github.com/rust-multiplatform/Base-Project-Template) pipeline.

version: 2.1

workflows:
  build:
    jobs:
      - platform_linux
      - shared

jobs:
  platform_linux:
    docker:
      - image: ghcr.io/rust-multiplatform/ci_image_bevy:main

        steps:
            - checkout
            - run: cargo --version

            # Build
            - run:
                  name: Build
                  command: cargo build --package platform_linux --release

            # Tests
            - run:
                  name: Tests
                  command: cargo test --no-default-features --no-fail-fast --package platform_linux --release

            # Upload Artifacts
            - store_artifacts:
                  path: target/release/platform_linux

  shared:
    docker:
      - image: ghcr.io/rust-multiplatform/ci_image_bevy:main

            # Build
            - run:
                  name: Build
                  command: wasm-pack build platform/webassembly/ --package platform_webassembly

            # Upload
            - store_artifacts:
                  path: ./platform/webassembly/pkg

            # Tests
            - run:
                  name: Run Tests
                  command: wasm-pack test --node platform/webassembly/ --package platform_webassembly

      # Upload Artifacts
      - store_artifacts:
          path: target/debug/libshare*
      - store_artifacts:
          path: target/debug/share*
      - store_artifacts:
          path: target/release/libshare*
      - store_artifacts:      
          path: target/release/share*
