# Please note that this CircleCI pipeline is much different from the upstream (https://github.com/rust-multiplatform/Base-Project-Template) pipeline.

version: 2.1

workflows:
  build:
    jobs:
      - platform_linux
      - shared

jobs:
  platform_linux:
    docker:
      - image: cimg/rust:1.65

    steps:
      - checkout
      - run: cargo --version

      # Build
      - run:
          name: Build (debug)
          command: cargo build --package platform_linux
      - run:
          name: Build (release)
          command: cargo build --package platform_linux --release

      # Tests
      - run:
          name: Run Tests (debug)
          command: cargo test --no-default-features --no-fail-fast --package platform_linux
      - run:
          name: Run Tests (release)
          command: cargo test --no-default-features --no-fail-fast --package platform_linux --release

      # Upload Artifacts
      - store_artifacts:
          path: target/debug/platform_linux
      - store_artifacts:
          path: target/release/platform_linux

  shared:
    docker:
      - image: cimg/rust:1.65

    steps:
      - checkout
      - run: cargo --version

      # Build
      - run:
          name: Build (debug)
          command: cargo build --package shared
      - run:
          name: Build (release)
          command: cargo build --package shared --release

      # Tests
      - run:
          name: Run Tests (debug)
          command: cargo test --no-default-features --no-fail-fast --package shared
      - run:
          name: Run Tests (release)
          command: cargo test --no-default-features --no-fail-fast --package shared --release

      # Upload Artifacts
      - store_artifacts:
          path: target/debug/libshare*
      - store_artifacts:
          path: target/debug/share*
      - store_artifacts:
          path: target/release/libshare*
      - store_artifacts:      
          path: target/release/share*
